project:
  type: book
  output-dir: docs

book:
  title: "The `openxlsx2` book"
  author: "Jan Marvin Garbuszus (JanMarvin) and `openxlsx2` authors"
  chapters:
    - index.qmd
    - chapters/01_introduction.qmd
    - chapters/openxlsx2_basic_manual.qmd
    - chapters/openxlsx2_number_and_string.qmd
    - chapters/openxlsx2_style_manual.qmd
    - chapters/conditional-formatting.qmd
    - chapters/openxlsx2_charts_manual.qmd
    - chapters/openxlsx2_formulas_manual.qmd
    - chapters/openxlsx2_pivot_tables.qmd
    - chapters/openxlsx2_data_validation.qmd
    - chapters/openxlsx2_form_control.qmd
    - chapters/openxlsx2_clone_and_copy.qmd
    - chapters/openxlsx2_upgrade_from_openxlsx.qmd
    - chapters/openxlsx2_extending.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual
